name: "Pre-commit"
description: 'Run and Settup Pre-commit'


runs:
  using: "composite"
  steps:

    - id: random-number-generator
      run: |
        #pip3 install --user --no-cache-dir pre-commit
        echo -------------- derd ------------------- ${PYTHONUSERBASE}
        ls /home/runner/.local/lib/python3.8/site-packages
        echo ----------------------
        ls /usr/lib/python3/dist-packages
        # Checkov
        #pip3 install --no-cache-dir checkov
        echo "/home/runner/cache" >> $GITHUB_PATH \
        export PATH="${PATH}:/home/runner/cache"
        echo "$PATH"
        echo $(ls /home/runner/cache)
      shell: bash

    - run: pre-commit run -a | tee something.txt
      shell: bash


    #- run: |
    #    pre-commit run --all-files | sed 's/\x1b\[[0-9;]*m//g' | tee output.md
    #    output=$(cat output.md)
    #    echo ::set-output name=precommit_output::$output
    #    echo Fileoutput $output
    #    echo ::debug:: $output
    #    git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
    #    git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
    #    git add .
    #    git commit -m "$INPUT_COMMIT"
    #    git push
    #  shell: bash
