name: "Pre-commit"
description: 'Runs antonbabenkos pre-commit'
author:  'User1935'
inputs:
  INFRACOST_API_KEY:
    description: 'API_KEY.'
    required: false

outputs:
  tf_actions_output:
    description: 'The Terragrunt outputs in JSON format.'



runs:
  using: 'docker'
  image: './Dockerfile'

