name: "Pre-commit"
description: 'Run and Settup Pre-commit'

inputs:
  filepath:
    description: "Name of file previously inserted with pre-commit output."
    required: false
    default: 'something.txt'

  type:
    description: "Type of formatting [pre-commit, terragrunt]"
    required: false
    default: 'pre-commit'

outputs:
  output:
    description: 'Content of stdout'
    value: ${{ steps.filecontent.outputs.FILECONTENT }}


runs:
  using: "composite"
  steps:
    - name: 'dependencies'
      run: |
        pip install html2text
        echo $(python ./.github/actions/pre-commit-output/dist/script.py)
      shell: bash
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}


    - name: 'fileContent'
      id: filecontent
      run: |
        echo "::set-output name=FILECONTENT::$(cat ./$INPUT_FILEPATH)"
      shell: bash
