name: "Pre-commit"
description: 'Run and Settup Pre-commit'

outputs:
  hash:
    description: "Hash of current versions of each module"
    value: ${{ steps.hash.outputs.HASH }}

  pythonpath:
    description: "Python path to the "
    value: ${{ steps.hash.outputs.PYTHONPATH }}

runs:
  using: "composite"
  steps:
    - id: hash
      run: |
        sudo apt install python3-testresources
        touch dep2
        echo "$(curl -s "https://api.github.com/repos/terraform-docs/terraform-docs/releases"/latest | grep -o -E -m 1 "https://.+?-linux-amd64.tar.gz")" >> dep2
        echo "$(curl -s "https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest" | grep -o -E -m 1 "https://.+?/terragrunt_linux_amd64")" >> dep2
        echo "$(curl -s "https://api.github.com/repos/accurics/terrascan/releases/latest" | grep -o -E -m 1 "https://.+?_Linux_x86_64.tar.gz")" >> dep2
        echo "$(curl -s "https://api.github.com/repos/terraform-linters/tflint/releases/latest" | grep -o -E -m 1 "https://.+?_linux_amd64.zip")" >> dep2
        echo "$(curl -s "https://api.github.com/repos/aquasecurity/tfsec/releases/latest" | grep -o -E -m 1 "https://.+?/tfsec-linux-amd64")" >> dep2
        echo "bananas" >> dep2
        echo "python3 -m site --usersite" >> dep2
        echo "::set-output name=HASH:: $(echo -n $(cat dep2) | sha256sum)"
        echo "::set-output name=PYTHONPATH:: $(python3 -m site --usersite)"
      shell: bash
