name: "Commit Changes"
description: 'Destroy and commits changes'

runs:
  using: "composite"
  steps:

    - name: 'Commit changes'
      run: |
         git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
         git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
         git pull
         git add .
         git commit -m "[no ci] Changes made by pipeline"
         git push
      shell: bash
