name: 'Apply planned settings'
on:
  push:
    branches:
      - 'main'

env:
  tf_working_dir: './CVT-IaC-Live-AZURE/ci-prod/ci-prod-vnet/'
  STORAGE_KEY: ${{secrets.STORAGE_KEY}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Hello:
      #if: github.event.pull_request.merged == true
      name: 'Generate matrix for build'
      runs-on: ubuntu-latest
      steps:
        - run: echo Hello World!
