name: TerraDoc

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 'Render terraform docs and push changes back to PR'
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ${{ env.tf_working_dir }}
          output-file: README.md
          output-method: inject
          git-push: "true" 
        
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}| xargs)"

      - name: echo the changed files
        run: |
          for i in ${{ steps.getfile.outputs.files }}
          do
              echo $i
          done
