name: 'Terragrunt GitHub Actions'
on:
   [push, pull_request]
  

env:
  tf_working_dir: './CVT-IaC-Live-AZURE/CF/CF-NonProd/L3/RG-1'
  STORAGE_KEY: ${{secrets.STORAGE_KEY}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERRAGRUNT_DOWNLOAD: '.terragrunt-cache'
jobs:
  pre-commit:
    name: 'Pre-Commit'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Pre-Commit'
        id: 'pre-commit'
        continue-on-error: true
        uses: ./actions/pre-commit

      - name: 'Make File with Content'
        run: |
          npm install turndown --save
          node ./actions/node/writeFile.js
        env:
          FILE_INPUT:  '${{ steps.pre-commit.outputs.filecontent }}'
          FILE_OUTPUT: './actions/node/tempfile.md'

      - name: Comment
        id: compost-comment
        uses: infracost/compost-action@master
        with:
          body-file: './actions/node/tempfile.md'
          github-token: '${{ env.GITHUB_TOKEN }}'
      #- name: Comment
      #  uses: actions/github-script@v6
      #  with:
      #    script: |
      #      github.rest.issues.createComment({
      #        issue_number: context.issue.number,
      #        owner: context.repo.owner,
      #        repo: context.repo.repo,
      #        body: '👋 Thanks for reporting!'
      #      })

  Pull_InfraCost:
    if: github.event_name == 'pull_request'
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false # This is recommended so the `terraform show` command outputs valid JSON

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.35.9
      
      - name: Install TgSwitch
        run: curl -L https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh | bash

      - name: Install TFenv
        run: brew install tfenv
      
      - name: 'ChangedFiles'
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: 'List Changed Files'
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done

      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          
      - name: Run Infracost
        run: infracost breakdown --path=${{ env.tf_working_dir }} --format=json --out-file=${{ env.tf_working_dir }}infracost.json
        
      - name: Post the comment
        uses: infracost/actions/comment@v1
        with:
          path: ${{ env.tf_working_dir }}infracost.json
          behavior: new

  Push_Terragrunt:
    if: github.event_name != 'pull_request'
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false # This is recommended so the `terraform show` command outputs valid JSON

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.35.9

      - name: Install TgSwitch
        continue-on-error: true
        run: curl -L https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh | bash

      - name: Install TFenv
        continue-on-error: true
        run: brew install tfenv

      - name: 'ChangedFiles'
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: 'List Changed Files'
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done

      

#the-commons-project/terragrunt-github-actions@master
