name: TerraDoc

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 'Render terraform docs and push changes back to PR'
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ${{ env.tf_working_dir }}
          output-file: README.md
          output-method: inject
          git-push: "true" 
